[package]
name = "cashu-starknet-node"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { workspace = true, features = ["macros"] }
tokio = { workspace = true, features = ["rt-multi-thread"] }
tower = { workspace = true, features = ["timeout"] }
tracing-subscriber = { workspace = true }
uuid = { workspace = true, features = ["serde"] }
parking_lot = { workspace = true, features = ["arc_lock"] }
serde = { workspace = true, features = ["derive"]}
serde_json = { workspace = true }
thiserror = { workspace = true }
num-traits = { workspace = true }
num-bigint = { workspace = true }
dotenv = { workspace = true }
primitive-types = { workspace = true }

nuts = { workspace = true }
cashu-starknet = { workspace = true }
invoice-payment-indexer = { workspace = true }
memory-db = { workspace = true }
keys-manager = { workspace = true }
starknet-types-core = { workspace = true }

sqlx = { workspace = true, features = ["postgres", "uuid"] }
rusqlite = { workspace = true }

axum-response-cache = { workspace = true, optional = true }

[features]
default = ["nut19"]
nut19 = ["nuts/nut19", "dep:axum-response-cache"]
uncollateralized = []

