[workspace]
resolver = "2"
members = [
  "crates/bin/node",
  "crates/bin/indexer",
  "crates/invoice-payment-indexer",
  "crates/keys-manager",
  "crates/memory-db",
  "crates/nuts",
  "crates/starknet",
]

[workspace.dependencies]
axum = "0.8.1"
axum-response-cache = "0.2.0"
http = "1.2.0"
tower = "0.5.2"
tokio = "1.42.0"
tracing-subscriber = "0.3.19"
serde_json = "1.0.134"
serde = { version = "1.0.216", features = ["derive"] }
thiserror = "2.0.9"
url = "2.5.4"
ciborium = "0.2.2"
bitcoin = "0.32.2"
num-derive = "0.4.2"
num-bigint = "0.4.2"
num-traits = "0.2.19"
once_cell = "1.20.2"
tracing = "0.1.41"
hex = "0.4.3"
starknet-types-core = "0.1.7"
uuid = "1.11.0"
lazy_static = "1.5.0"
dotenv = "0.15.0"
sqlx = "0.8.2"
parking_lot = "0.12.3"
rand = "0.8.5"
starknet-core = "0.12.1"
futures = "0.3.31"
anyhow = "1.0.95"
apibara-core = { git = "https://github.com/apibara/dna.git", rev = "f1b782e0e86b"}
apibara-sdk = { git = "https://github.com/apibara/dna.git", rev = "f1b782e0e86b"}
rusqlite = "0.32.0"
primitive-types = "0.13.1"
pin-project = "1.1.9"
async-rwlock = "1.3.0"


# Local crates
nuts = { path = "crates/nuts" }
cashu-starknet = { path = "crates/starknet" }
memory-db  = { path = "crates/memory-db" }
keys-manager  = { path = "crates/keys-manager" }
invoice-payment-indexer = { path = "crates/invoice-payment-indexer" }





