[package]
name = "mint"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { workspace = true, features = ["macros"] }
tokio = { workspace = true, features = ["rt-multi-thread"] }
tracing-subscriber = { workspace = true }
nuts = { workspace = true }
cashu-starknet = { workspace = true }
uuid = {workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"]}
thiserror = { workspace = true }
memory-db = { workspace = true }
num-traits = { workspace = true }
dotenv = { workspace = true }
sqlx = { workspace = true, features = ["postgres", "uuid"] }
parking_lot = { workspace = true, features = ["arc_lock"] }
keys-manager = { workspace = true }
