[package]
name = "cashu-starknet"
version = "0.1.0"
edition = "2021"

[dependencies]
starknet-types-core = { workspace = true, features = ["num-traits", "serde"] }
nuts = { workspace = true }
serde = { workspace = true }
num-traits = { workspace = true }
num-derive = { workspace = true }

