[package]
name = "cashu-starknet-invoice-indexer"
version = "0.1.0"
edition = "2024"

[dependencies]
invoice-payment-indexer = { workspace = true }

starknet-types-core = { workspace = true }

tokio = { workspace = true, features = ["rt-multi-thread"] }
rusqlite = { workspace = true, features = ["bundled"] }
futures = { workspace = true }

anyhow = { workspace = true }
dotenvy = {workspace = true }
